# netlify.toml
# This file tells Netlify where to find your serverless functions
# and which folder to publish for the live site.

[build]
  # This tells Netlify that your website files (index.html) are in the root directory.
  publish = "."

[functions]
  directory = "netlify/functions/"
